# Generated by Django 5.2.6 on 2025-09-27 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_messages', models.IntegerField()),
                ('neutral_count', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('harassment_count', models.IntegerField(default=0)),
                ('extortion_count', models.IntegerField(default=0)),
                ('neutral_percentage', models.FloatField(default=0.0)),
                ('positive_percentage', models.FloatField(default=0.0)),
                ('harassment_percentage', models.FloatField(default=0.0)),
                ('extortion_percentage', models.FloatField(default=0.0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='AppIA.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Análisis',
                'verbose_name_plural': 'Reportes de Análisis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='AppIA.message')),
            ],
            options={
                'verbose_name': 'Análisis de Mensaje',
                'verbose_name_plural': 'Análisis de Mensajes',
            },
        ),
    ]
